//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LytkovaSidneva
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public string NameOrder { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
